coverage:
  precision: 2
  round: nearest
  range: "75...100"
  status:
    project:
      default:
        target: "75%"
        threshold: "0%"
    patch: false
    changes: false
comment:
  layout: "diff, files"