coverage:
  precision: 2
  round: nearest
  range: "40...75"
  status:
    project:
      default:
        target: "80%"
        threshold: "5%"
    patch: false
    changes: false
comment:
  layout: "diff, files"